apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
group = 'com.github.pedroSG94'

android {
    compileSdkVersion 32

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 32
        versionCode 199
        versionName "1.9.9"
    }
    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'proguard-rules.pro'
        }
    }
    namespace = "com.pedro.rtsp"
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}
